'use strict';
// Adventure progress extends v1 profiles. Old tests, badges and certificates stay valid.
const FINAL_TASKS=[
 [Q('Help Nara get ready for Art. She needs to draw a straight line. Take a ___.',['ruler','spoon','pillow'],'Use a ruler to draw a straight line.','📏','Things we use'),Q('Nara has her ruler. Art starts after English. Which lesson is before Art?',['English','Science','PE'],'English comes before Art in this plan.','📅','Times and lessons'),Q('After Art, Nara needs a book for her project. Where can she borrow one?',['Library','Canteen','Toilet'],'Borrow a book from the library.','📚','Use the clues')],
 [Q('Help Bima make lunch. First, he must wash his hands. What does he need?',['Soap and water','A pillow','A school bag'],'Wash your hands with soap and water before you make food.','💧','Follow steps'),Q('His hands are clean. The soup is ready. Choose something to eat it with.',['A spoon','A comb','A ruler'],'Use a spoon to eat soup.','🥄','Things we use'),Q('Lunch is over. Some soup is left. Where can Bima keep it cool?',['In the fridge','On the bed','In the wardrobe'],'A fridge keeps food cool.','🧊','Use the clues')],
 [Q('Help Sari with two jobs: send a letter and buy fruit. The post office closes first. Where should she go first?',['Post office','Market','Park'],'Send the letter first because the post office closes first.','✉️','Use the clues'),Q('Sari has sent the letter. She still needs bananas. Where should she go next?',['Market','Hospital','Bank'],'Buy bananas at the market.','🥕','Follow steps'),Q('Sari finds a lost bag near the market. Who can help her report it?',['Police officer','Farmer','Cook'],'Tell a police officer about the lost bag.','👮','Jobs')],
 [Q('Help Kira make a study space. The room is dark. What should she do first?',['Turn on the lamp.','Hide the books.','Close her eyes.'],'Turn on a lamp so Kira can see.','💡','Follow steps'),Q('The room is bright. Two books are near Kira. Complete: ___ are my books.',['These','This','That'],'Use these for two or more things near you.','📚','Sentences'),Q('Kira has light and books. The desk is full of plates. What will help her study?',['Move the plates and put the books on the desk.','Put more plates on the desk.','Turn off the lamp.'],'A clear desk with books is a good place to study.','📝','Use the clues')]
];
const FINAL_NAMES=['Ready for Art','Lunch at Home','Two Jobs in Town','A Place to Study'];
const STYLES=[{id:'classic',name:'Classic',need:0,hue:0,color:'#9aefbe'},{id:'ocean',name:'Ocean Blue',need:3,hue:115,color:'#70d6ff'},{id:'sun',name:'Sun Gold',need:6,hue:300,color:'#ffce64'},{id:'violet',name:'Purple Star',need:9,hue:195,color:'#c8a1ff'},{id:'crystal',name:'Crystal Light',need:12,hue:45,color:'#eefff5'}];
function adventure(p=profile()){
 if(!p)return null;
 if(!p.adventure)p.adventure={version:1,areas:Array.from({length:4},(_,i)=>({missions:p.done[i]?Array(12).fill(true):Array.from({length:12},(_,j)=>j<(p.checkpoints[i]?.index||0)),clean:Array(12).fill(false),final:false,finalCheckpoint:null})),words:{},style:'classic'};
 for(let i=0;i<4;i++){const a=p.adventure.areas[i];a.masteredIds??=a.clean.flatMap((ok,j)=>ok?[MISSION_BANKS[i][j].id]:[]);}
 return p.adventure;
}
function starsFor(i,p=profile()){const a=adventure(p).areas[i];return [a.missions.every(Boolean),a.clean.every(Boolean),a.final];}
function starCount(p=profile()){return [0,1,2,3].reduce((n,i)=>n+starsFor(i,p).filter(Boolean).length,0);}
function currentStyle(){const a=adventure(),style=STYLES.find(s=>s.id===a?.style);return style&&starCount()>=style.need?style:STYLES[0];}
function restoration(i){return adventure().areas[i].missions.filter(Boolean).length;}
function restorationText(i){const n=restoration(i);return n===12?'The world is full of life!':n>=8?'The garden is growing.':n>=4?'The lights are on.':'Bring back the light.';}
function spriteTile(index,cls=''){return `<span class="sprite-ui ${cls}" style="background-position:${index%4*100/3}% ${Math.floor(index/4)*100/3}%" aria-hidden="true"></span>`;}
function starLine(i){const stars=starsFor(i);return `<span class="mastery-stars" aria-label="${stars.filter(Boolean).length} of 3 stars">${stars.map(s=>s?'★':'☆').join(' ')}</span>`;}
const worldBeforeAdventure=world;
world=function(){worldBeforeAdventure();if(!profile())return;const a=adventure(),n=a.areas.reduce((sum,x)=>sum+x.missions.filter(Boolean).length,0);const scene=$('.world');scene.style.setProperty('--recovery',n/48);scene.classList.add('restoring-world');document.querySelectorAll('.island').forEach((el,i)=>{const r=restoration(i);el.classList.add('life-'+Math.floor(r/4));if(i===1)el.style.top='49%';el.insertAdjacentHTML('beforeend',`<div class="island-life">${r>=4?'<span class="world-light" aria-label="Lights on">✦</span>':''}${r>=8?spriteTile(15):''}${r===12?spriteTile(i===0?8:i===1?10:i===2?11:14):''}<span>${starLine(i)}<small>${r}/12 · ${restorationText(i)}</small></span></div>`);});$('.map-bottom').insertAdjacentHTML('beforebegin',`<div class="adventure-tools">${button('📖 My Word Book','word-book','btn small')}${button('★ '+starCount()+'/12 · Stars & Style','wardrobe','btn small gold')}</div>`);save();};
const openAreaBeforeAdventure=openArea;
openArea=function(i){openAreaBeforeAdventure(i);if(screen!=='intro'||area!==i)return;const a=adventure().areas[i],m=AREA_META[i];$('.intro .card').innerHTML=`<h3>12 missions from 50 questions.</h3><div class="mission-steps"><span><b>1–4 · Discover</b><small>Use daily words.</small></span><span><b>5–8 · Connect</b><small>Follow the clues.</small></span><span><b>9–12 · Solve</b><small>Think and act.</small></span></div><p>${m.controls}</p><div class="row" style="margin-top:15px">${button(profile().checkpoints[i]?'Continue missions →':'Start missions →','play','btn primary')}${button('Word help','vocab','btn')}</div><div class="area-stars">${starLine(i)} <span>${restorationText(i)}</span><p style="font-size:15px;margin:12px 0">Finish the missions, then help ${m.guide} in a 3-step Final Challenge.</p><div class="row">${a.missions.every(Boolean)?button(a.final?'Play challenge again':'Final Challenge →','final-challenge','btn small gold'):''}${a.final||profile().tests[i]?button('Area test','test','btn small'):''}${button('Star goals','star-goals','btn small ghost')}</div></div>`;};
function starGoals(){const a=adventure().areas[area];modal(`<h2>Three stars in ${AREA_META[area].place}</h2><div class="star-goals"><p>${starsFor(area)[0]?'★':'☆'} Finish all 12 missions. <b>${a.missions.filter(Boolean).length}/12</b></p><p>${starsFor(area)[1]?'★':'☆'} Answer 12 different questions correctly on your first try, without hints. <b>${a.clean.filter(Boolean).length}/12</b></p><p>${a.final?'★':'☆'} Finish the 3 steps in the Final Challenge.</p></div><p>You can play again to earn missing stars. Stars you earn stay yours. Stars and styles do not change your test score.</p><div class="row">${button('Close','close','btn primary')}</div>`);}
const showProfileBeforeAdventure=showProfile;
showProfile=function(){showProfileBeforeAdventure();$('.page-title').insertAdjacentHTML('afterend',`<div class="row adventure-profile">${button('📖 My Word Book','word-book','btn')}${button('★ '+starCount()+'/12 · Stars & Style','wardrobe','btn gold')}</div>`);};
function wardrobe(){if(!profile())return;closeModal();setScreen('wardrobe');const count=starCount(),chosen=currentStyle();$('#main').innerHTML=`<section class="page"><div class="page-title"><div><div class="eyebrow">YOUR REWARDS</div><h2>Stars & Style</h2><p>★ ${count}/12 stars · Choose a new look for your runner and robot.</p></div>${button('← Map','map','btn small')}</div><div class="scroll"><div class="style-list">${STYLES.map(s=>`<article class="style-card ${chosen.id===s.id?'equipped':''}"><div class="style-preview" style="filter:hue-rotate(${s.hue}deg)">${spriteTile(12,'large')}<span class="runner-preview"></span></div><h3>${s.name}</h3><p>${s.need?`${s.need} stars`:'Your first style'}</p>${button(chosen.id===s.id?'Wearing this':count>=s.need?'Wear this':'🔒 '+(s.need-count)+' more stars','wear-style','btn small',`data-id="${s.id}" ${chosen.id===s.id||count<s.need?'disabled':''}`)}</article>`).join('')}</div><div class="star-area-list">${AREA_META.map((m,i)=>`<article class="card"><h3>${m.place} ${starLine(i)}</h3><p>12 missions: ${restoration(i)}/12<br>Different questions, no hints: ${adventure().areas[i].clean.filter(Boolean).length}/12<br>Final Challenge: ${adventure().areas[i].final?'Done':'Not done'}</p></article>`).join('')}</div><p>Styles change your look. They do not give extra lives, time or test points.</p></div></section>`;}
function wearStyle(id){const s=STYLES.find(x=>x.id===id);if(!s||starCount()<s.need)return;adventure().style=s.id;save();wardrobe();toast(s.name+' is ready to wear.');}
// Each entry has a local picture/icon, a short example and a contextual practice question.
const WORD_BOOK=[];
for(const bank of [...MISSION_BANKS,...FINAL_TASKS,...TESTS])for(const q of bank){const key=q.answer.toLowerCase();if(!WORD_BOOK.some(w=>w.id===key))WORD_BOOK.push({id:key,word:q.answer,icon:q.icon,example:q.why,question:q});}
function rememberWord(q,ok){const entry=WORD_BOOK.find(w=>w.id===q.answer.toLowerCase());if(!entry)return;const words=adventure().words,w=words[entry.id]??={seen:0,correct:0,weak:false,practice:0};w.seen++;if(ok)w.correct++;else{w.weak=true;w.practice=0;}save();}
let bookMode='all',bookPractice=null;
function wordBook(mode=bookMode){if(!profile())return;bookMode=mode;closeModal();setScreen('word-book');const words=adventure().words,learned=WORD_BOOK.filter(w=>words[w.id]),weak=learned.filter(w=>words[w.id].weak),list=mode==='practice'?weak:learned;$('#main').innerHTML=`<section class="page"><div class="page-title"><div><div class="eyebrow">WORDS FROM YOUR ADVENTURE</div><h2>My Word Book</h2><p>${learned.length}/${WORD_BOOK.length} word cards · ${weak.length} to practise</p></div>${button('← Map','map','btn small')}</div><div class="row book-tabs">${button('All my words','word-all',mode==='all'?'btn primary small':'btn small')}${button('Words to practise','word-weak',mode==='practice'?'btn primary small':'btn small')}${weak.length?button('Practise these words →','book-practice','btn small gold'):''}</div><div class="scroll word-scroll"><div class="word-grid">${list.map(w=>`<article class="word-card"><span class="word-picture">${wordPicture(w)}</span><div><h3>${esc(w.word)}</h3><p>${esc(w.example)}</p><small>${words[w.id].weak?'↻ Practise this · '+words[w.id].practice+'/2':'✓ In your book'}</small></div></article>`).join('')||`<article class="card full"><h3>${mode==='practice'?'No words to practise.':'Your book starts here.'}</h3><p>${mode==='practice'?'Good work! Play more missions to find new words.':'Make your first move in a mission to collect a word card.'}</p>${button('Go to map','map','btn primary')}</article>`}</div></div></section>`;}
function wordPicture(w){const icons={'📏':1,'📚':9,'📘':0,'✏️':2,'🎒':3,'🥄':4,'🍽️':5,'🍲':6,'🪥':7,'🏫':8,'🏥':11,'🌳':15};const index=icons[objectIcon(w.word)]??icons[w.icon];return index===undefined?esc(w.icon):spriteTile(index,'large');}
function practiseBook(){const words=adventure().words,weak=WORD_BOOK.filter(w=>words[w.id]?.weak);if(!weak.length){wordBook('practice');return;}bookPractice={queue:shuffled(weak).slice(0,5),index:0,correct:0};bookQuestion();}
function bookQuestion(){const w=bookPractice.queue[bookPractice.index];bookPractice.options=shuffled(w.question.options);bookPractice.locked=false;modal(`<div class="eyebrow">WORD PRACTICE · ${bookPractice.index+1}/${bookPractice.queue.length}</div><h2>Read and try again.</h2><p>${esc(w.question.text)}</p><div class="answers">${bookPractice.options.map((v,i)=>button(esc(v),'book-answer','btn',`data-i="${i}"`)).join('')}</div><p>No clock. No lives lost. Give 2 correct practice answers to clear a word.</p><div class="row">${button('Back to my book','word-weak','btn ghost')}</div>`);}
function bookAnswer(i){if(!bookPractice||bookPractice.locked||!bookPractice.options[i])return;bookPractice.locked=true;const w=bookPractice.queue[bookPractice.index],record=adventure().words[w.id],ok=bookPractice.options[i]===w.question.answer;if(ok){bookPractice.correct++;record.practice++;if(record.practice>=2)record.weak=false;}else{record.practice=0;record.weak=true;}save();sfx(ok);modal(`<h2>${ok?'Good work!':'Read and learn.'}</h2><p>${esc(w.example)}</p><p>${record.weak?record.practice+'/2 correct practice answers.':'This word is ready!'}</p><div class="row">${button('Next →','book-next','btn primary')}</div>`);}
function nextBookQuestion(){if(++bookPractice.index<bookPractice.queue.length)bookQuestion();else{const n=bookPractice.correct;wordBook('practice');toast('Practice done. '+n+' correct answers.');bookPractice=null;}}
// Every physical answer goes through the same grading gate. Focusing does not grade.
selectAnswer=function(i){if(screen!=='play'||!engine||game.feedback||game.solved||!$('#overlay').hidden||i<0||i>2)return;if(area===0){engine.focusCard=i;toast('Answer '+(i+1)+': run and jump to this platform.');}if(area===1){engine.aimTarget=i;toast('Aim set to '+(i+1)+'. Press Shoot or pull the ball.');}if(area===2)engine.lane=i;if(area===3){engine.focusCard=i;const p=engine.cardPos(i);engine.slash={a:{x:p.x-140,y:p.y+55},b:{x:p.x+140,y:p.y-55}};answerByMove(i);}};
function answerByMove(i){if(screen!=='play'||!game||game.feedback||game.solved||game.over||!$('#overlay').hidden||!game.options[i])return;const ok=game.options[i]===game.q.answer;game.selected=i;const first=!game.recorded;if(first){game.recorded=true;game.answered++;if(ok&&!game.helped)game.correct++;if(game.helped)game.assisted++;}game.firstClean=first&&ok&&!game.helped;rememberWord(game.q,ok);if(!ok){game.combo=0;game.failed=true;engine.cooldown=1.6;engine.gateY=20;if(area===0){engine.player.x=Math.max(40,engine.player.x-125);engine.player.y=307;engine.player.vy=0;}if(loseLife('Wrong answer.'))return;game.feedback=true;storeRunHealth();modal(`<div class="eyebrow">TRY AGAIN · ${game.lives} LIVES LEFT</div><h2>Read the clue again.</h2><p>${esc(game.q.why)}</p><p>Your move chose: ${esc(game.options[i])}. This word is in My Word Book for practice.</p><div class="row">${button('Try another move','retry-choice','btn primary')}</div>`);return;}
 game.solved=true;engine.target=i;game.combo=(game.combo||0)+1;sfx(true);if(area===0||area===2){engine.burst(i);engine.pendingFinish=.7;engine.ready=false;}if(area===1){engine.burst(i);engine.impact(i);engine.pendingFinish=.95;}if(area===3)engine.cut(i);
}
function runSnapshot(index=game.index){return {questionIds:game.questionIds?.slice(),options:index===game.index?game.options?.slice():null,timeLeft:index===game.index?game.timeLeft:null,timeLimit:index===game.index?game.timeLimit:null,index,correct:game.correct,answered:game.answered,assisted:game.assisted,points:game.points,lives:game.lives,over:!!game.over,final:!!game.final,recorded:index===game.index&&!!game.recorded,helped:index===game.index&&!!game.helped,failed:index===game.index&&!!game.failed};}
checkpoint=function(index=game?.index){if(!game||!profile())return;const cp=runSnapshot(index);if(game.final)adventure().areas[area].finalCheckpoint=cp;else profile().checkpoints[area]=cp;save();};
storeRunHealth=function(){if(game&&profile())checkpoint();};
const startPlayBeforeAdventure=startPlay;
startPlay=function(){const cp=profile()?.checkpoints[area];startPlayBeforeAdventure();if(game&&cp&&screen==='play'){restoreMissionState(cp);}if(game)game.final=false;if(screen==='play')checkpoint();};
function restoreMissionState(cp){game.recorded=!!cp.recorded;game.helped=!!cp.helped;game.failed=!!cp.failed;if(Number.isFinite(cp.timeLeft)&&cp.timeLeft>0){game.timeLeft=cp.timeLeft;game.timeLimit=cp.timeLimit||missionSeconds();paintClock('#mission-clock',game.timeLeft);}}

const nextMissionBeforeAdventure=nextMission;
nextMission=function(){if(game.final){if(game.index>=3){finishFinal();return;}renderFinalMission();return;}nextMissionBeforeAdventure();if(screen==='play'&&engine)prepareMovement();};
function prepareMovement(){engine.ready=true;engine.target=-1;engine.aimTarget=1;game.firstClean=false;game.failed=false;const instructions=['Jump onto the platform with your answer.','Aim at your answer. Pull the ball or use Shoot.','Run into the gate with your answer.','Cut the fruit box with your answer.'];$('.choice-bar').setAttribute('aria-label',area===0?'Platform names':area===1?'Set shot aim':area===2?'Choose a lane':'Cut an answer');$('.play-controls').insertAdjacentHTML('afterbegin',`<span class="move-instruction">${instructions[area]}</span>`);if(area===1){const b=$('[data-action="assist-shot"]');if(b)b.textContent='Shoot at my aim';}if(area===0)document.querySelectorAll('.answer-mini').forEach(b=>b.title='Find this platform and jump onto it.');}
const hintBeforeAdventure=hint;
hint=function(){hintBeforeAdventure();if(game&&!game.solved){game.firstClean=false;checkpoint();}};
const timeoutBeforeAdventure=missionTimeout;
missionTimeout=function(){if(!game.over&&!game.feedback){game.failed=true;game.firstClean=false;rememberWord(game.q,false);}timeoutBeforeAdventure();};
const finishMissionBeforeAdventure=finishMission;
finishMission=function(){if(!game||!game.solved||game.feedback||game.over)return;const old=starCount(),a=adventure().areas[area],index=game.index;let message='';if(!game.final){const was=restoration(area);a.missions[index]=true;if(game.firstClean&&!game.helped&&!game.failed&&game.q.id){if(!a.masteredIds.includes(game.q.id))a.masteredIds.push(game.q.id);const count=Math.max(a.clean.filter(Boolean).length,Math.min(12,a.masteredIds.length));a.clean=Array.from({length:12},(_,j)=>j<count);}const now=restoration(area);if(now!==was&&[4,8,12].includes(now))message=restorationText(area);}
 finishMissionBeforeAdventure();const earned=starCount()-old;if(message||earned)$('#overlay .modal').insertAdjacentHTML('afterbegin',`<div class="world-reward">${message?'✦ '+message:''} ${earned?'★ New star!':''}</div>`);if(game.final){const next=$('[data-action="next-mission"]');if(next)next.textContent=index===2?'Finish challenge →':'Next step →';}if(starCount()>old)showNewStyle(old);save();};
function showNewStyle(old){const unlocked=STYLES.find(s=>s.need>old&&s.need<=starCount());if(unlocked)toast(unlocked.name+' unlocked! Open Stars & Style on the map.');}
finishPlay=function(){stopEngine();const p=profile();p.done[area]=true;p.checkpoints[area]=null;save();setScreen('practice-result');$('#main').innerHTML=`<section class="page"><div class="page-title"><div><div class="eyebrow">12 MISSIONS DONE</div><h2>${restorationText(area)}</h2><p>${starLine(area)} ${game.correct}/12 correct first answers in this run</p></div>${spriteTile(14,'large')}</div><div class="card"><h2>Final Challenge: ${FINAL_NAMES[area]}</h2><p style="margin-top:20px">Help ${AREA_META[area].guide} with 3 linked tasks. Read each clue and make your move. Start with 3 lives. Finish the challenge to earn a star and open the area test.</p><div class="row" style="margin-top:26px">${button('Start Final Challenge →','final-challenge','btn primary')}${button('My Word Book','word-book','btn')}${button('World map','map','btn')}</div></div></section>`;};
function startFinal(restart=false){const a=adventure().areas[area];if(!a.missions.every(Boolean)){toast('Finish the 12 missions first.');return;}closeModal();setScreen('play');const cp=restart?null:a.finalCheckpoint;game=cp?{...cp}:{index:0,correct:0,answered:0,assisted:0,points:0,lives:3};game.final=true;game.resumeOptions=cp?.options;game.combo=0;if(game.over||game.lives<=0){showGameOver();return;}nextMission();if(cp)restoreMissionState(cp);if(screen==='play')checkpoint();}
function renderFinalMission(){nextMissionBeforeAdventure();prepareMovement();$('.hud .row').innerHTML=`<span class="eyebrow">FINAL CHALLENGE</span><span>${FINAL_NAMES[area]} · <b>${game.index+1}/3</b></span>`;$('.mission-prompt small').textContent='HELP '+AREA_META[area].guide.toUpperCase()+' · STEP '+(game.index+1);}

function finishFinal(){stopEngine();const old=starCount(),a=adventure().areas[area];a.final=true;a.finalCheckpoint=null;profile().done[area]=true;save();setScreen('final-result');$('#main').innerHTML=`<section class="page"><div class="page-title"><div><div class="eyebrow">FINAL CHALLENGE DONE</div><h2>You helped ${AREA_META[area].guide}!</h2><p>${FINAL_NAMES[area]} · 3/3 steps done</p></div>${spriteTile(14,'large')}</div><div class="card"><h2>${starLine(area)} Your world is ready.</h2><p style="margin-top:20px">Next: answer 10 test questions. Get 70 or more to find the Word Crystal. Your stars, styles and game points do not change the test score.</p><div class="row" style="margin-top:26px">${button('Start area test →','test','btn primary')}${button('Stars & Style','wardrobe','btn gold')}${button('World map','map','btn')}</div></div></section>`;showNewStyle(old);confetti();}
const startTestBeforeAdventure=startTest;
startTest=function(){const a=adventure().areas[area];if(!a.final&&!profile().tests[area]){toast('Finish the Final Challenge to open this test.');if(a.missions.every(Boolean))startFinal();return;}startTestBeforeAdventure();};
const restartAreaBeforeAdventure=restartArea;
restartArea=function(){if(game?.final)startFinal(true);else restartAreaBeforeAdventure();};
const showGameOverBeforeAdventure=showGameOver;
showGameOver=function(){showGameOverBeforeAdventure();if(game.final){$('#overlay .modal p').textContent='You reached step '+Math.min(game.index+1,3)+' in the Final Challenge.';const b=$('[data-action="restart-area"]');if(b)b.textContent='Try challenge again';}};
// Tint only the character sprite; earned looks cannot change physics or assessment.
const AdventureBaseEngine=GameEngine;
GameEngine=class extends AdventureBaseEngine{
 constructor(...args){super(...args);this.aimTarget=1;}
 update(dt){if(game?.feedback||game?.over||this.paused)return;super.update(dt);}
 drawRunner(...args){this.ctx.save();this.ctx.filter='hue-rotate('+currentStyle().hue+'deg)';super.drawRunner(...args);this.ctx.restore();}
 drawHumanRunner(){this.ctx.save();this.ctx.filter='hue-rotate('+currentStyle().hue+'deg)';super.drawHumanRunner();this.ctx.restore();}
 drawHouse(){super.drawHouse();if(!game.solved){const p=this.targetPosition(this.aimTarget);this.text('YOUR AIM',p.x,p.y-52,14,'#ffe0a4','center');}}
 draw(){super.draw();if(!game.solved){const c=this.ctx,n=restoration(area);if(n>=4){c.save();c.globalAlpha=.4;c.fillStyle=currentStyle().color;c.beginPath();c.arc(18,53,5,0,Math.PI*2);c.fill();c.restore();}if(n>=8)this.sprite(15,area===2?85:1175,area===2?205:260,65);if(n>=12)this.sprite(14,area===2?1140:25,area===2?200:250,40);}}
};
document.addEventListener('click',e=>{const b=e.target.closest('[data-action]');if(!b||b.disabled)return;const a=b.dataset.action;if(a==='word-book'||a==='word-all')wordBook('all');else if(a==='word-weak')wordBook('practice');else if(a==='book-practice')practiseBook();else if(a==='book-answer')bookAnswer(Number(b.dataset.i));else if(a==='book-next')nextBookQuestion();else if(a==='wardrobe')wardrobe();else if(a==='wear-style')wearStyle(b.dataset.id);else if(a==='star-goals')starGoals();else if(a==='final-challenge')startFinal();});
for(const p of db.profiles)adventure(p);

const testAnswerBeforeAdventure=testAnswer;
testAnswer=function(i){if(quiz&&!quiz.locked){const q=quiz.questions[quiz.index];rememberWord(q,i>=0&&quiz.options[i]===q.answer);}testAnswerBeforeAdventure(i);};
const guideBeforeAdventure=guide;
guide=function(){guideBeforeAdventure();$('.grid').insertAdjacentHTML('afterbegin',`<article class="card full"><h3>Your moves bring the world to life.</h3><p>Each area has 50 questions. A new game picks 12: four for each level. Continue a saved game to keep the same questions. Finish the missions, then help a friend with 3 tasks in the Final Challenge. Finish the challenge to open the area test. After 4 missions, lights come on. After 8, plants grow. After 12, the world is full of life.</p><p style="margin-top:12px">My Word Book keeps word cards with pictures and examples. Wrong answers go into Words to practise. Give 2 correct practice answers to clear a word. Practice has no clock and uses no lives.</p><p style="margin-top:12px">Each area has 3 stars: finish the missions; answer 12 different questions correctly on your first try without hints; finish the Final Challenge. Earn 3, 6, 9 or 12 stars for a new style. Open Stars & Style on the map to wear it.</p></article>`);};

addEventListener('pagehide',()=>{if(screen==='play'&&game&&!game.feedback&&!game.solved)checkpoint();});
