'use strict';
// Presentation and feedback only. Assessment, collisions, lives and saves stay in their own layers.
function reducedEffects(){return db.settings.reduced||!!window.matchMedia?.('(prefers-reduced-motion: reduce)').matches;}
const AREA_FEEL=[{verb:'Jump',color:'#81efbb',dark:'#143e3e',sprite:8},{verb:'Shoot',color:'#ffd08b',dark:'#463443',sprite:10},{verb:'Run',color:'#7fdaff',dark:'#183b51',sprite:15},{verb:'Cut',color:'#cfadff',dark:'#34294d',sprite:14}];
function missionDots(done,total=12){return `<span class="mission-dots" aria-label="${done} of ${total} done">${Array.from({length:total},(_,i)=>`<i class="${i<done?'done':''}"></i>`).join('')}</span>`;}
home=function(){setScreen('home');const p=profile();$('#main').innerHTML=`<section class="start quest-start"><div class="home-logos" aria-label="Education logos"><img class="ministry-logo" src="assets/logo-tut-wuri.png" alt="Tut Wuri Handayani - Kemendikdasmen"><img src="assets/logo-sobat-smp.png" alt="Sobat SMP"><img src="assets/logo-quality-education.png" alt="Quality education for all"><img src="assets/logo-ramah.png" alt="Kemendikdasmen RAMAH"></div><div class="quest-title"><div class="eyebrow">THINGS AROUND ME · ENGLISH ADVENTURE</div><h1>WORD<br><span>CRYSTAL</span><br>QUEST<span class="title-dot">.</span></h1><p>Four worlds need their light back.<br>Read the clues. Make your move.</p><div class="row quest-start-actions">${button(p?'Continue adventure ▶':'Let’s play ▶','start','btn primary')}${button('⛶','start-fullscreen','btn ghost','aria-label="Play in full screen"')}</div><div class="quest-download">${button('↓ Download offline game','offline','btn small ghost')}</div></div><div class="quest-art" aria-hidden="true"><div class="quest-orbit"></div><div class="hero-crystal">${spriteTile(14,'large')}</div><div class="hero-robot">${spriteTile(12,'large')}</div><div class="hero-spark spark-one">✦</div><div class="hero-spark spark-two">✧</div><div class="hero-spark spark-three">✦</div></div><div class="hero-callout"><span class="eyebrow">${p?'WELCOME BACK, '+esc(p.name):'YOUR ADVENTURE STARTS HERE'}</span><p>${p?`${completed()}/4 crystals · ${starCount()}/12 stars`:'200 questions. A new quest each time.'}</p></div><div class="world-teasers" aria-label="Four ways to play">${AREA_META.map((m,i)=>`<div class="world-teaser" style="--area-accent:${AREA_FEEL[i].color}"><span class="teaser-icon">${spriteTile(AREA_FEEL[i].sprite)}</span><span><b>0${i+1} · ${AREA_FEEL[i].verb}</b><small>${m.name}</small></span></div>`).join('')}</div></section>`;};
const worldBeforePolish=world;
world=function(){worldBeforePolish();if(!profile())return;const next=[0,1,2,3].find(i=>isOpen(i)&&(!adventure().areas[i].final||!profile().tests[i]||profile().tests[i].best<70));document.querySelectorAll('.island').forEach((el,i)=>{el.style.setProperty('--area-accent',AREA_FEEL[i].color);el.classList.toggle('next-world',i===next);el.insertAdjacentHTML('beforeend',missionDots(restoration(i)));});const text=$('.world-head p');if(text)text.textContent=next===undefined?'All crystals found! Find more stars and word cards.':'Your next world: '+AREA_META[next].name+'.';};
function paintPlayStyle(){if(screen!=='play'||!engine)return;const feel=AREA_FEEL[area];$('#main').style.setProperty('--area-accent',feel.color);$('#main').style.setProperty('--area-dark',feel.dark);$('.playfield').classList.add('quest-arena');const done=game.final?game.index:game.index,total=game.final?3:12;$('.playfield').insertAdjacentHTML('beforeend',`<div class="arena-progress" aria-label="Mission progress">${missionDots(done,total)}</div>`);$('.mission-prompt .symbol').classList.add('clue-symbol');$('.mission-prompt').classList.add('quest-clue');}
const prepareBeforePolish=prepareMovement;
prepareMovement=function(){prepareBeforePolish();paintPlayStyle();};
function syncAim(){if(!engine||screen!=='play')return;const focused=area===0?engine.focusCard:area===1?engine.aimTarget:area===2?engine.lane:engine.focusCard;document.querySelectorAll('.answer-mini').forEach((b,i)=>{b.classList.toggle('aiming',i===focused&&!game.solved);b.setAttribute('aria-pressed',String(i===focused));});}
const selectBeforePolish=selectAnswer;
selectAnswer=function(i){selectBeforePolish(i);syncAim();};
const answerBeforePolish=answerByMove;
answerByMove=function(i){const canAnswer=screen==='play'&&game&&!game.solved&&!game.feedback&&!game.over&&$('#overlay').hidden;if(!canAnswer){answerBeforePolish(i);return;}answerBeforePolish(i);if(game.solved&&engine){engine.cheer=1;engine.cheerText=game.combo>=3?game.combo+' IN A ROW!':'GREAT MOVE!';engine.cheerColor=AREA_FEEL[area].color;}};
const loseBeforePolish=loseLife;
loseLife=function(reason){const result=loseBeforePolish(reason);if(engine&&!game.over){engine.hitFlash=.25;engine.cheerText='TRY AGAIN';engine.cheer=.65;engine.cheerColor='#ffc4a7';}return result;};
const finishBeforePolish=finishMission;
finishMission=function(){const canFinish=game?.solved&&!game.feedback&&!game.over;finishBeforePolish();if(!canFinish)return;const box=$('#overlay .modal');if(!box)return;box.classList.add('mission-win');const total=game.final?3:12;box.insertAdjacentHTML('afterbegin',`<div class="win-banner"><span class="win-crystal">${spriteTile(14)}</span><div><span class="eyebrow">${game.final?'STEP COMPLETE':'GREAT WORK, EXPLORER!'}</span><div class="win-progress">${missionDots(game.index+1,total)}<b>${game.index+1}/${total}</b></div></div><span class="combo-tag">${game.combo>=2?'×'+game.combo:'✓'}</span></div>`);if(!reducedEffects()){tone(523,.13,'sine',.07);setTimeout(()=>tone(659,.13,'sine',.07),110);setTimeout(()=>tone(784,.22,'sine',.07),220);}};
const PolishBaseEngine=GameEngine;
GameEngine=class extends PolishBaseEngine{
 constructor(...args){super(...args);this.cheer=0;this.hitFlash=0;this.cheerText='';this.jumpRing=0;this.jumpX=0;this.jumpY=0;this.feedbackTrail=[];this.feedbackClock=0;this.lastFocus=-1;}
 keyDown(key){const grounded=this.player.ground;super.keyDown(key);if(this.type===0&&grounded&&!this.player.ground){this.jumpRing=.32;this.jumpX=this.player.x;this.jumpY=this.player.y;}syncAim();}
 pointerDown(e){super.pointerDown(e);syncAim();}
 update(dt){if(this.paused||game?.over||game?.feedback)return;this.cheer=Math.max(0,this.cheer-dt);this.hitFlash=Math.max(0,this.hitFlash-dt);this.jumpRing=Math.max(0,this.jumpRing-dt);this.feedbackTrail.forEach(p=>p.life-=dt);this.feedbackTrail=this.feedbackTrail.filter(p=>p.life>0);super.update(dt);if(game.feedback||game.over)return;if(!reducedEffects()&&this.type===2&&this.speed>.2){this.feedbackClock+=dt;if(this.feedbackClock>.08){this.feedbackClock=0;this.feedbackTrail.push({x:this.carX+(Math.random()-.5)*22,y:316,life:.4});}}const focus=this.type===1?this.aimTarget:this.type===2?this.lane:this.focusCard;if(focus!==this.lastFocus){this.lastFocus=focus;syncAim();}}
 // Local artwork brings each arena closer to its map while keeping targets readable.
 drawSchool(){const c=this.ctx;c.save();c.globalAlpha=.22;this.sprite(8,970-this.cam*.16,185,260);this.sprite(15,105-this.cam*.08,229,160);c.restore();super.drawSchool();if(this.jumpRing>0&&!reducedEffects()){c.save();c.globalAlpha=this.jumpRing/.32;c.strokeStyle=AREA_FEEL[0].color;c.lineWidth=3;c.beginPath();c.ellipse(this.jumpX-this.cam,this.jumpY,14+(1-this.jumpRing/.32)*29,5+(1-this.jumpRing/.32)*6,0,0,Math.PI*2);c.stroke();c.restore();}}
 drawHouse(){const c=this.ctx;c.save();c.globalAlpha=.17;this.sprite(10,333,181,270);c.restore();super.drawHouse();}
 drawRace(){super.drawRace();const c=this.ctx;c.save();c.globalAlpha=.55;this.sprite(15,66,165,135);this.sprite(11,1165,75,104);c.restore();if(!reducedEffects())for(const p of this.feedbackTrail){c.save();c.globalAlpha=p.life*.8;c.strokeStyle=currentStyle().color;c.lineWidth=3;c.beginPath();c.moveTo(p.x,p.y);c.lineTo(p.x,p.y+18*(1-p.life/.4));c.stroke();c.restore();}}
 drawNinja(){const c=this.ctx;c.save();c.globalAlpha=.12;this.sprite(14,615,172,285);c.restore();super.drawNinja();}
 draw(){super.draw();const c=this.ctx;if(this.cheer>0){const progress=1-this.cheer;c.save();const w=300,x=465,y=88-(reducedEffects()?0:Math.max(0,progress)*12);c.globalAlpha=Math.min(1,this.cheer*5);this.rounded(x,y,w,55,14,'#091d31ed',this.cheerColor);this.text(this.cheerText,615,y+36,25,this.cheerColor,'center','Quest');c.restore();}if(this.hitFlash>0&&!reducedEffects()){c.save();c.globalAlpha=this.hitFlash*.8;c.strokeStyle='#ffc4a7';c.lineWidth=9;c.strokeRect(5,5,1220,323);c.restore();}}
};
// Scripts load before the first interaction; show the refreshed home immediately.
home();
